name: 'amplify-preview-actions'
description: 'This action builds and deploys your AWS Amplify pull request preview for public repository'
inputs:
  branch_name:
    description: 'GitHub branch name to deploy'
    required: true
  amplify_command:
    description: 'amplify command: SUPPORTED: [deploy, delete]'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch_name }}
    - ${{ inputs.amplify_command }}
branding:
  icon: 'git-commit'
  color: 'blue'
